import type { Metadata } from "next";
import AlternateLinks from '../../components/AlternateLinks'
//import { unstable_setRequestLocale } from 'next-intl/server';
//import { PropsWithChildren } from 'react';
//import { routing } from '../../i18n/routing';

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

export default async function LocaleLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  /*
  was
  
  export function generateStaticParams() {
    // Зазвичай локалі містяться в routing.locales або в конфігурації Next.js
    const locales = ['en', 'uk', 'ru']; // Додайте всі доступні локалі
    return locales.map((locale) => ({ locale }));
  }
  
  
  or
  
  import { routing } from '../../i18n/routing';
  export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
  }
  
  
  export const metadata: Metadata = {
    title: "META Create Next App",
    description: " META Generated by create next app",
  };
  */

  /*
    export default async function LocaleLayout({ children, params: { locale } }: PropsWithChildren<{ params: { locale: string } }>) {
      const messages = await getMessages();
  
      unstable_setRequestLocale(locale);*/

  return (
    <html lang={locale}>
      <meta name="google-site-verification" content="95VB15Q3SzIYfiI_FFZaaBPj3DB2UeMoRvu5CznGsNk" />
      <meta name="yandex-verification" content="78b622fe0ecb0c26" />
      <meta name='wmail-verification' content='249e0e3ca4fddc09ba49d010bd758023' />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <AlternateLinks />
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );

}